version: 0.0
os: linux

files:
  - source: ./from-the-sake-of-god
    destination: /towards-eternity

hooks:
  DownloadBundle:
    - location: ./codedeploy/downloadBundle.sh
      timeout: 180
      runas: ubuntu
  AfterInstall:
    - location: ./codedeploy/afterInstall.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 180
      runas: ubuntu
  BeforeInstall:
    - location: ./codedeploy/beforeInstall.sh
      timeout: 180
      runas: ubuntu
  Install:
    - location: ./codedeploy/install.sh
      timeout: 180
      runas: ubuntu