version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu

hooks:
  DownloadBundle:
    - location: ./codedeploy/downloadBundle.sh
      timeout: 180
      runas: ubuntu
  ApplicationStop:
    - location: ./codedeploy/applicationStop.sh
      timeout: 180
      runas: ubuntu
  AfterInstall:
    - location: ./codedeploy/afterInstall.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 180
      runas: ubuntu
  BeforeInstall:
    - location: ./codedeploy/beforeInstall.sh
      timeout: 180
      runas: ubuntu
  Install:
    - location: ./codedeploy/install.sh
      timeout: 3000
      runas: ubuntu