---
version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/openjdk:8-jdk-stretch # The primary container where steps are run
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: bill
          MYSQL_USER: varaddesai
          MYSQL_PASSWORD: csye6225

    steps:
      - checkout
      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready..
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 30`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI;
          command: |
            sudo apt-get update
            sudo apt-get install default-mysql-client
      - run:
          name: Step into web application
          command: |
            pwd
            ls
            cd ..
      - run:
          name: create archive of your application
          command: |
            tar -czvf webapp.tar.gz project

      - run:
          name: send the archive to s3 bucket
          command: |
            echo "this command will send the archive to s3 bucket"


  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch # The primary container where steps are run
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: bill
          MYSQL_USER: varaddesai
          MYSQL_PASSWORD: csye6225

    steps:
      - checkout
      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready..
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 30`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI;
          command: |
            sudo apt-get update
            sudo apt-get install default-mysql-client
      - run:
          name: Step into web application
          command: |
            pwd
            ls
            cd ..
      - run:
          name: create archive of your application
          command: |
            pwd
            ls
            tar -czvf webapp.tar.gz project

      - run:
          name: send the archive to s3 bucket
          command: |
            echo "this command will send the archive to s3 bucket"

workflows:
  version: 2
  pr-check-workflow:
    jobs:
      - pr_check
  build-deploy-workflow:
    jobs:
      - build