---
version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/openjdk:8-jdk-stretch # The primary container where steps are run
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: bill
          MYSQL_USER: varaddesai
          MYSQL_PASSWORD: csye6225

    steps:
      - checkout
      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready..
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 30`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI;
          command: |
            sudo apt-get update
            sudo apt-get install default-mysql-client
      - run:
          name: Step into web application
          command: |
            # go to a correct folder
                     pwd
                     ls
            # create archive of your application and send it to ec2 instance
                     tar -czvf webapp.tar.gz project
                     scp -i aws-circleci webapp.tar.gz ubuntu@3.136.236.245:scp

            # ssh to ec2 instance
                     ssh -i aws-circleci ubuntu@3.136.236.245

            # remove webapp folder and untar new one
                     cd scp
                     rm -rf *
                     tar -xzvf webapp.tar.gz

            # create build
                     cd project
                     mvn clean install

  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch # The primary container where steps are run
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: bill
          MYSQL_USER: varaddesai
          MYSQL_PASSWORD: csye6225

    steps:
      - checkout
      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready..
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 30`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI;
          command: |
            sudo apt-get update
            sudo apt-get install default-mysql-client
      - run:
          name: Step into web application
          command: |
            # go to a correct folder
            pwd
            cd ..

            # create archive of your application and send it to ec2 instance
            tar -czvf webapp.tar.gz webapp
            scp -i aws-circleci webapp.tar.gz ubuntu@3.136.236.245:scp

            # ssh to ec2 instance
            ssh -i aws-circleci ubuntu@3.136.236.245

            # remove webapp folder and untar new one
            cd scp
            rm -rf *
            tar -xzvf webapp.tar.gz

            # create build
            cd webapp
            mvn clean install


workflows:
  version: 2
  pr-check-workflow:
    jobs:
      - pr_check
  build-deploy-workflow:
    jobs:
      - build
